Modified task 1

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 # This script installs and configures nginx
 sudo apt-get install -y nginx
+if [ $? -eq 0 ]
+then
 echo -e \
 "http {
 	root /var/www/school;
@@ -17,3 +19,13 @@ mkdir -p /var/www/school
 echo "Hello World!" > \
 	/var/www/school/index.html
 service nginx start
+if [ $? -ne 0 ]
+then
+	echo "Problem starting  ngnix"
+	exit 1
+fi
+else
+	echo " Could not install nginx
+	exit 1
+fi
+exit 0
